---
authors:
  - Cludus Dev Team
license_file: LICENSE
name: commons
tags: [routing, networking, facts, frr]
namespace: cludus
readme: README.md
description: Ansible Collection for Cludus setup
repository: https://github.com/cludus/clu-ansible-roles
issues: https://github.com/cludus/clu-ansible-roles/issues
version: "0.2.0"
dependencies:
  ansible.builtin: ">=1.2.0"