
- name: ensure Alpine community repository is enabled
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    regexp: '^#\s*http://dl-cdn.alpinelinux.org/alpine/v3.22/community'
    line: 'http://dl-cdn.alpinelinux.org/alpine/v3.22/community'
    state: present
  when: ansible_facts['distribution'] == "Alpine"

- name: install ufw
  ansible.builtin.package:
    name:
      - ufw
    update_cache: true
    state: present

- name: deny all incoming traffic by default
  community.general.ufw:
    default: deny
    direction: incoming

- name: deny all outgoing traffic by default
  community.general.ufw:
    default: deny
    direction: outgoing

- name: deny forwarded/routed traffic by default
  community.general.ufw:
    default: deny
    route: true

- community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    from_ip: "{{ item.ip }}"
  loop: "{{ firewall.admin_ips }}"

- name: allow all outgoing traffic
  community.general.ufw:
    rule: allow
    direction: out

- community.general.ufw:
    rule: allow
    route: true

- community.general.ufw:
    rule: allow
    port: "{{ hostvars[inventory_hostname].vpn.listening_port }}"
    proto: udp
  when: hostvars[inventory_hostname].vpn is defined

- community.general.ufw:
    rule: allow
    port: "89"
  when: hostvars[inventory_hostname].ospf is defined

- community.general.ufw:
    rule: allow
    port: "179"
  when: hostvars[inventory_hostname].bgp is defined

- community.general.ufw:
    state: enabled

- name: add ufw service
  ansible.builtin.service:
    name: ufw
    state: restarted
    enabled: true