
- name: install ufw
  ansible.builtin.package:
    name:
      - ufw
    update_cache: true
    state: present
  when: ansible_facts['distribution'] == "Alpine"

- name: deny all incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming

- name: allow all outgoing traffic
  community.general.ufw:
    default: allow
    direction: outgoing

- community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    from_ip: "{{ hostvars[inventory_hostname].firewall.admin_ip }}"