- name: adding resolv.conf
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  register: resolv

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname].hostname }}"

- name: Add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.ip }}  {{ item.hostname }}'  # Replace with your desired IP and hostname
    line: '{{ item.ip }}  {{ item.hostname }}'   # Replace with your desired IP and hostname
    state: present
    mode: 0644
  become: yes
  loop: "{{ hosts }}"

- name: restart on resolv.conf added
  ansible.builtin.reboot:
  when: resolv.changed
