- name: adding resolv.conf
  template:
    dest: /etc/resolv.conf
    src: resolv.conf.j2
    owner: root
    group: root
    mode: '0444'
  register: resolv

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname].hostname }}"

- name: adding config routes script ubuntu
  template:
    dest: /etc/hosts
    src: hosts.j2
    owner: root
    group: root
    mode: '0444'

- name: restart on resolv.conf added
  ansible.builtin.reboot:
  when: resolv.changed
