
- name: enable service staticroute
  ansible.builtin.service:
    name: staticroute
    enabled: yes
  when: ansible_facts['distribution'] == "Alpine"

- name: iptables
  ansible.builtin.package:
    name:
      - iptables-persistent
    update_cache: true
    state: latest
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: adding config routes script
  template:
    dest: /etc/route.conf
    src: route.conf.j2
    owner: root
    group: root
    mode: '0755'
  register: routescfg
  when: ansible_facts['distribution'] == "Alpine"

- name: adding config routes script ubuntu
  template:
    dest: /etc/networkd-dispatcher/routable.d/config_routes
    src: config_routes.j2
    owner: root
    group: root
    mode: '0755'
  register: ubtroutescfg
  when: ansible_facts['distribution'] == "Ubuntu"

- name: adding config routes script debian
  template:
    dest: /etc/network/if-up.d/config_routes
    src: config_routes.j2
    owner: root
    group: root
    mode: '0755'
  register: debroutescfg
  when: ansible_facts['distribution'] == "Debian"

- name: unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
  when: routescfg.changed or ubtroutescfg.changed or debroutescfg.changed

- name: enable service staticroute
  ansible.builtin.service:
    name: staticroute
    enabled: yes
    state: restarted
  when: ansible_facts['distribution'] == "Alpine"

- name: enable service networkd-dispatcher
  systemd:
    name: networkd-dispatcher.service
    enabled: yes
    state: restarted
  when: ansible_facts['distribution'] == "Ubuntu"
  