- name: download a file from a URL
  ansible.builtin.get_url:
    url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.133.0/otelcol_0.133.0_linux_amd64.tar.gz"
    dest: "/tmp/otelcol.tar.gz"
    mode: '0644'

- name: unarchive a tar.gz file
  ansible.builtin.unarchive:
    src: "/tmp/otelcol.tar.gz"
    dest: "/tmp/otelcol"
    remote_src: yes
    creates: "/tmp/otelcol"
    strip_components: 1

- name: copy otelcol to bin folder
  ansible.builtin.copy:
    src: /tmp/otelcol/otelcol
    dest: /usr/bin/otelcol
    remote_src: yes