
- name: install docker
  ansible.builtin.package:
    name:
      - docker
    update_cache: true
    state: present
  when: ansible_facts['distribution'] == "Alpine"

- name: enable service staticroute
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == "Alpine"