name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'the type of release'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract current version
        id: extract-current-version
        run: |
              version=$(yq '.version' galaxy.yml)
              echo "current version: $version"
              echo "release type: ${{ github.event.inputs.release_type }}"
              IFS='.' read -r major minor patch <<< "$version"
              if [ "${{ github.event.inputs.release_type }}" == "patch" ]; then
                echo "current-version=$major.$minor.$patch" >> $GITHUB_OUTPUT
                patch=$((patch+1))
              elif [ "${{ github.event.inputs.release_type }}" == "minor" ]; then
                minor=$((minor+1))
                patch=0
              else
                major=$((major+1))
                minor=0
                patch=0
              fi
              echo "new version: $major.$minor.$patch"
              echo "new-version=$major.$minor.$patch" >> $GITHUB_OUTPUT

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract-current-version.outputs.new-version }}

      - name: Bump up version
        run: |
          yq -i ".version = \"${{ steps.extract-current-version.outputs.new-patch-version }}\"" galaxy.yml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bump up version"
          git push
