name: Release

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump up version
        run: |
              version=$(yq '.version' galaxy.yml)
              IFS='.' read -r major minor patch <<< "$version"
              patch=$((patch+1))
              # yq -i ".version = \"$major.$minor.$patch\"" galaxy.yml
              echo $major.$minor.$patch

#      - name: Release
#        uses: softprops/action-gh-release@v2
#        if: github.ref_type == 'tag'